// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmL5e3o6sv6kT64GFZE57mGKn6HiTiyIw',
    appId: '1:577799551756:web:d587360cfa233309382729',
    messagingSenderId: '577799551756',
    projectId: 'pj-prueba-8cce2',
    authDomain: 'pj-prueba-8cce2.firebaseapp.com',
    databaseURL: 'https://pj-prueba-8cce2-default-rtdb.firebaseio.com',
    storageBucket: 'pj-prueba-8cce2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsp8k6I9GzSLhN1v2kLWCrtG_3U3ol2oA',
    appId: '1:577799551756:android:009a43e510e914b0382729',
    messagingSenderId: '577799551756',
    projectId: 'pj-prueba-8cce2',
    databaseURL: 'https://pj-prueba-8cce2-default-rtdb.firebaseio.com',
    storageBucket: 'pj-prueba-8cce2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA8KToKnMDwqsiTVqyvg4p5Nww2ng3c_0',
    appId: '1:577799551756:web:a659d77b9335653a382729',
    messagingSenderId: '577799551756',
    projectId: 'pj-prueba-8cce2',
    authDomain: 'pj-prueba-8cce2.firebaseapp.com',
    databaseURL: 'https://pj-prueba-8cce2-default-rtdb.firebaseio.com',
    storageBucket: 'pj-prueba-8cce2.firebasestorage.app',
  );

}